modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
    modId = "aether_redux"
    version = "${file.jarVersion}"
    displayName = "The Aether: Redux"
    displayURL = "https://github.com/Zepalesque/Aether-Redux-Issue-Tracker"
    logoFile = "redux.png"
    credits = "The Aether Team, Aerod, BrianIsBro, Emile van Kreiken, 345boneshoss, RazorDevs, unroman, Parallel113, IcyCrystal, ModdingLegacy, Builderdog841, Jonathing, LlamaLad7, Shimmer.shine"
    authors = "Zepalesque"
    description = '''
The Aether: Redux is an expansive addon mod for the well-known Aether mod, adding a wide variety of new content ranging from several new biomes to an overhaul to the mod's first dungeon. There are a variety of other new features as well!

A whole lot of new mob models have also been implemented, which are all configurable as well, so you can choose between Redux's upgraded versions and the originals if you prefer them.

You can also configure Redux's built-in asset overrides resource pack, using the new in-game config system created specifically for this, so you can change the appearance of various parts of the mod to your hearts content!

Speaking of configuration, the mod also has a ton of configuration options, so check those out, as you could very well prefer certain options over others.
 '''
[[dependencies.aether_redux]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.20.1-,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "aeroblender"
    mandatory = true
    versionRange = "[0,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "deep_aether"
    mandatory = false
    versionRange = "[1.20.1-,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "lost_aether_content"
    mandatory = false
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "aether_genesis"
    mandatory = false
    versionRange = "[1.20.1-,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId = "ancient_aether"
    mandatory = false
    versionRange = "[0.6.0-,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.aether_redux]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2.2,)"
    ordering="NONE"
    side="BOTH"


